version: "3.8"

services:
  db:
    image: postgres:12.4
    container_name: cookle-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cookle_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d/"

  api:
    container_name: cookle-api
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    container_name: cookle-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
